"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Providers from "./providers";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children, session,
}: Readonly<{
  children: React.ReactNode;
  session: Session
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Providers>
            <StoreProvider>{children}</StoreProvider>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
